env:
  browser: true
  node: true
  es6: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  process: true
parserOptions:
  ecmaVersion: 2018
rules:
  'no-undef': 0
  'quotes': ['error', 'single']
